version: '3.8'

services:
  nodetodo-app:
    build: .
    container_name: nodetodo-app
    ports:
      - "3000:3000"   # Host:Container
    environment:
      - PORT=3000
    restart: unless-stopped
